hw04 completed
petrenko-alex/otus-golang-hw pull request #4
Opened 2023-07-06 15:40 UTC by petrenko-alex

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-07 14:00 UTC, ityulkanov requested changes

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache.go
> +	return listItem, ok
а зачем нам нужна вот эта функция? Только чтобы вынести moveToFront вызов?

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache.go
> +}
имхо, эта функция тут избыточна

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache.go
> +}
не стоит создавать функции там где можно ограничиться комментарием

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache_test.go
> +package hw04lrucache_test
вам не нужно менять имя модуля

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache_test.go
> +	hw04lrucache "github.com/petrenko-alex/otus-golang-hw/hw04_lru_cache"
```suggestion
	 "github.com/petrenko-alex/otus-golang-hw/hw04_lru_cache"
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache_test.go
> +		c := hw04lrucache.NewCache(10)
```suggestion
		c := NewCache(10)
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache_test.go
> +		c := hw04lrucache.NewCache(5)
```suggestion
		c := NewCache(5)
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache_test.go
> +			c.Set(hw04lrucache.Key(strconv.Itoa(i)), i)
```suggestion
			c.Set(Key(strconv.Itoa(i)), i)
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/cache_test.go
> +			c.Get(hw04lrucache.Key(strconv.Itoa(rand.Intn(1_000_000))))
```suggestion
			c.Get(Key(strconv.Itoa(rand.Intn(1_000_000))))
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list.go
> +
кмк тут можно было бы сделать и проверку на len(list) != 0

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list.go
> +	l.pushItemToFront(i)
так тоже можно, но это будет не совсем оптимально по памяти. Более эффективно будет всё же дописать перестановку указателей

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list.go
>  }
здесь не o(1) получается, а o(n)

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list_test.go
> +package hw04lrucache_test
тут тоже самое - менять имя пакета не нужно. достаточно иметь в названии файла _test.go

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list_test.go
> +		l := hw04lrucache.NewList()
```suggestion
		l := NewList()
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list_test.go
> +		l := hw04lrucache.NewList()
### 
```suggestion
		l := NewList()
```

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list_test.go
> +		l := hw04lrucache.NewList()
и остальные ниже по списку

2023-07-07 14:00 UTC, engineer-go commented on hw04_lru_cache/list_test.go
> +func TestNewFilledList(t *testing.T) {
очень необычно видеть покрытие приватных методов тестами, но похвально, что вы заморочились и написали тесты даже для этого функционала

2023-07-07 14:00 UTC, ityulkanov commented on hw02_unpack_string/go.sum
> +github.com/stretchr/objx v0.1.0 h1:4G4v2dO3VZwixGIRoQ5Lfboy6nUhCyYzaqnIAPPhYs4=
хм, не понимаю, у вас в десятке файлов изменения именно в этой строке, по идее go mod меняется автоматически. Вы руками правили его, или это тула какая то лишние правки внесла?

2023-07-07 18:16 UTC, petrenko-alex commented on hw04_lru_cache/cache.go
> +	return listItem, ok
этот кусок кода; получение элемента и его "актуализация" (скажем так) явно повторялся у меня. Соблюдая DRY решил вынести в метод...

2023-07-07 18:19 UTC, petrenko-alex commented on hw04_lru_cache/cache_test.go
> +package hw04lrucache_test
На последнем уроке по тестированию обозначили этот подход как blackbox тестирование. Когда меня название пакета теряешь доступ к не экспортируемым методам и явно ограничиваешься тестированием только публичных...

2023-07-07 18:19 UTC, petrenko-alex commented on hw04_lru_cache/cache_test.go
> +	hw04lrucache "github.com/petrenko-alex/otus-golang-hw/hw04_lru_cache"
Это мне так goland импортирует. Это как-то настраивается?

2023-07-07 18:21 UTC, petrenko-alex commented on hw04_lru_cache/list_test.go
> +func TestNewFilledList(t *testing.T) {
Этот метод оставил экспортируемым. У меня на нем основаны все остальные тесты, поэтому посчитал нужным быть уверенным и в нем :)

2023-07-07 18:22 UTC, petrenko-alex commented on hw02_unpack_string/go.sum
> +github.com/stretchr/objx v0.1.0 h1:4G4v2dO3VZwixGIRoQ5Lfboy6nUhCyYzaqnIAPPhYs4=
вот тоже не понял, что это.
Менял версию GoLand на EAP ревизию. В ней GoLand начал упорно предлагать эти изменения. Rollback не помогал. Выглядит странно, но вроде все работало...

2023-07-07 18:22 UTC, petrenko-alex commented on hw04_lru_cache/cache.go
> +}
В целом, согласен, оборачивать одну строку в отдельный метод, наверное избыточно.

2023-07-10 12:16 UTC, ityulkanov commented on hw02_unpack_string/go.sum
> +github.com/stretchr/objx v0.1.0 h1:4G4v2dO3VZwixGIRoQ5Lfboy6nUhCyYzaqnIAPPhYs4=
Я не использую early access так как там не только половина плагинов может не работать, но и могут быть баги, которые мешают работать. ИМХО эти изменения не должны тут быть. А если работать в той же 2023.1.3 тоже меняет эти файлы?

2023-07-10 12:16 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	return listItem, ok
Ну тут мы создали 7 строк кода, заменяя 4. Не уверен что в этом есть необходимость. Но можем оставить, не критично.

2023-07-10 12:16 UTC, ityulkanov commented on hw04_lru_cache/cache_test.go
> +package hw04lrucache_test
Ну по идее нам внутренние методы тестировать и нет большой нужды, т.к. мы в первую очередь должны смотреть как отрабатывает сам контракт. Но раз уж сделали, можно и оставить.

2023-07-10 12:16 UTC, ityulkanov commented on hw04_lru_cache/cache_test.go
> +	hw04lrucache "github.com/petrenko-alex/otus-golang-hw/hw04_lru_cache"
Интересно, что мой instance наоборот посчитал этот импорт избыточным. Борьба ИИ) Нет, такой настройки не видел. Обычно алиасы нужны когда у вас 2 импортируемых пакета имеют одинаковые методы, тут вроде бы не тот случай.

2023-07-10 13:23 UTC, petrenko-alex commented on hw04_lru_cache/cache_test.go
> +	hw04lrucache "github.com/petrenko-alex/otus-golang-hw/hw04_lru_cache"
Изменил имя на "."

2023-07-10 13:54 UTC, petrenko-alex commented on hw02_unpack_string/go.sum
> +github.com/stretchr/objx v0.1.0 h1:4G4v2dO3VZwixGIRoQ5Lfboy6nUhCyYzaqnIAPPhYs4=
Нашел, это действительно баг EAP 
https://youtrack.jetbrains.com/issue/GO-15065/GoLand-2023.2-always-modify-go.sum-files-on-startup

Изменения "уходят", если вызвать go mod tidy. Но из-за специфики структуры репозитория, приходится вызывать go mod tidy в каждой папке.

EAP версию пришлось использовать, т.к. на основной закончился trial. На vs code пересаживаться не могу :)

2023-07-11 19:29 UTC, petrenko-alex commented on hw04_lru_cache/cache.go
> +	return listItem, ok
удалил метод

2023-07-11 19:31 UTC, petrenko-alex commented on hw04_lru_cache/cache.go
> +}
удалил метод

2023-07-11 19:33 UTC, petrenko-alex commented on hw04_lru_cache/cache.go
> +}
удалил метод

2023-07-12 09:45 UTC, engineer-go approved these changes

2023-07-13 14:18 UTC, merged